language: cpp

sudo: required
dist: trusty

addons:
 apt:
  packages:
  - gcc
  - libappindicator3-dev
  - libgtk-3-dev

script:
- make

notifications:
 email:
  recipients:
  - dawidd0811@gmail.com
  on_success: always
  on_failure: always
